/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Notification = {
  _id: string;
  _type: "notification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  type?:
    | "enrollment"
    | "completion"
    | "certificate_ready"
    | "certificate_expiring"
    | "inactivity";
  read?: boolean;
  message?: string;
  courseId?: string;
  createdAt?: string;
};

export type Enrollment = {
  _id: string;
  _type: "enrollment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  courseId?: string;
  enrolledAt?: string;
  country?: string;
  source?: "auto" | "manual";
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  courseId?: string;
  tier?: "participation" | "accomplishment";
  score?: number;
  issuedAt?: string;
  expiresAt?: string;
  blobUrl?: string;
};

export type SurveyResponse = {
  _id: string;
  _type: "surveyResponse";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  courseId?: string;
  csatScore?: number;
  npsScore?: number;
  completedAt?: string;
  gender?: string;
  ageGroup?: string;
  healthWorkerType?: string;
  country?: string;
};

export type LessonProgress = {
  _id: string;
  _type: "lessonProgress";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  lessonId?: string;
  lessonShortId?: string;
  courseId?: string;
  completed?: boolean;
  preTestScore?: number;
  postTestScore?: number;
  scormData?: string;
  timeSpent?: number;
  completedAt?: string;
  gender?: string;
  ageGroup?: string;
  healthWorkerType?: string;
  country?: string;
};

export type Quiz = {
  _type: "quiz";
  questionText?: string;
  options?: Array<string>;
  correctIndex?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  type?: "text" | "scorm" | "quiz";
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  scormPackage?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  scormEntryUrl?: string;
  scormVersion?: "1.2" | "2004";
  questions?: Array<
    {
      _key: string;
    } & Quiz
  >;
  quizRole?: "pre-test" | "post-test" | "self-assessment";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type CourseModule = {
  _id: string;
  _type: "courseModule";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type CourseModuleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "courseModule";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  modules?: Array<
    {
      _key: string;
    } & CourseModuleReference
  >;
  passingScore?: number;
  country?: Array<string>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type ForumPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "forumPost";
};

export type CommentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "comment";
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: AuthorReference;
  content?: string;
  parentPost?: ForumPostReference;
  parentComment?: CommentReference;
  publishedAt?: string;
};

export type DataInsight = {
  _id: string;
  _type: "dataInsight";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  metric?: string;
  value?: number;
  change?: number;
  rawData?: string;
  category?: string;
};

export type JobOpening = {
  _id: string;
  _type: "jobOpening";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  company?: string;
  location?: string;
  type?: "full-time" | "contract" | "remote";
  description?: string;
  applyUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type DirectoryItem = {
  _id: string;
  _type: "directoryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "fintech" | "ecommerce" | "saas";
  location?: Geopoint;
  website?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type ForumPost = {
  _id: string;
  _type: "forumPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    externalUrl?: string;
    _type: "image";
  };
  clerkId?: string;
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Notification
  | Enrollment
  | Certificate
  | SurveyResponse
  | LessonProgress
  | Quiz
  | SanityFileAssetReference
  | Lesson
  | Slug
  | LessonReference
  | CourseModule
  | CourseModuleReference
  | Course
  | AuthorReference
  | ForumPostReference
  | CommentReference
  | Comment
  | DataInsight
  | JobOpening
  | SanityImageAssetReference
  | DirectoryItem
  | SanityImageCrop
  | SanityImageHotspot
  | Geopoint
  | ForumPost
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;
